### ISSUE TITLE
Upload Image?

### ISSUE THREAD

**Issue by sturgill** [ejholmes/active_admin_editor#24] opened 2013-02-27 06:33 UTC
If I use the 1.0.5 gem, I am presented with the file selector button and can opt to upload an image. However, the image upload process fails.  I have saved the CORS configuration to the bucket.

If I try using the 1.0.6 gem, I am never even presented with the option of uploading a file.

Any chance you have an idea of what I'm screwing up?

**Comment by ejholmes** [comment] 2013-02-27 07:10
You've added an initializer and [configured s3](https://github.com/ejholmes/active_admin_editor#uploads)? What's the output of the following:

``` bash
$ rails c
>> ActiveAdmin::Editor.configuration.s3_configured?
```

**Comment by sturgill** [comment] 2013-02-28 13:42
`true`

**Comment by ejholmes** [comment] 2013-02-28 18:34
What about `window.AA.editor_config.uploads_enabled`, in the javascript console?

**Comment by chrismcleod** [comment] 2013-03-04 23:29
false

**Comment by ejholmes** [comment] 2013-03-05 00:05
Maybe try clearing the rails cache?

```
rm -rf tmp/cache
```

**Comment by chrismcleod** [comment] 2013-03-05 14:58
No luck.  Also, it works for me locally, but not on heroku.  Anything special I should do for heroku?

**Comment by chrismcleod** [comment] 2013-03-13 14:32
In the chrome console, it shows the compiled erb javascript results in "uploads_enabled=!1".

**Comment by ejholmes** [comment] 2013-03-15 01:07
I haven't been able to reproduce this, but I have a possible fix for this in a branch:

``` ruby
gem 'active_admin_editor', github: 'ejholmes/active_admin_editor', branch: 'issue-24'
```

Could you give it a whirl and let me know if it fixes the issue you're seeing?

**Comment by chrismcleod** [comment] 2013-03-15 13:21
Well I just went in to the javascript code and saw you were using .js.erb and realized I had 

``` ruby
initialize_on_compile = false
```

in environments/production.rb.  Changing that to true and enabling the experimental environment config for my heroku app by running: 

``` ruby
heroku labs:enable user-env-compile -a myapp
```

In the terminal for that app fixed the problem for me.  

For those with similar symptoms, this was happening because my application was not being initialized before it was compiled.  The compilation step compiles all the javascript and evaluates erb at that time.  On heroku, because the environment variables aren't normally available during the slug compilation, the active_admin initializer was not getting the proper values.  ie: 

``` ruby
config.editor.s3_bucket = ENV['S3_BUCKET_NAME']
config.editor.aws_access_key_id = ENV['AWS_ACCESS_KEY_ID']
config.editor.aws_access_secret = ENV['AWS_ACCESS_SECRET_KEY']
```

does not work since those will all be set to nil because environment variables are not available at compile time.  However, heroku identified this problem, and so release that labs feature above.

**Comment by ejholmes** [comment] 2013-03-15 17:44
Sweet. I'll add some notes to the readme.

**Closed as completed** 2013-03-15 17:49 UTC
